ALTER TABLE ventas
ADD COLUMN IF NOT EXISTS id_tarjeta_puntos INT REFERENCES tarjetas_puntos(id_tarjeta);

ALTER TABLE ventas
ADD COLUMN IF NOT EXISTS puntos_ganados NUMERIC(12,2) NOT NULL DEFAULT 0;

ALTER TABLE ventas
ADD COLUMN IF NOT EXISTS monto_pagado_dinero NUMERIC(12,2) DEFAULT 0,
ADD COLUMN IF NOT EXISTS monto_pagado_puntos NUMERIC(12,2) DEFAULT 0,
ADD COLUMN IF NOT EXISTS puntos_usados NUMERIC(12,2) DEFAULT 0;


ALTER TABLE ventas
ADD COLUMN IF NOT EXISTS subtotal_sin_descuento NUMERIC(12,2) DEFAULT 0,
ADD COLUMN IF NOT EXISTS descuento_ofertas NUMERIC(12,2) DEFAULT 0;

ALTER TABLE venta_detalle
ADD COLUMN IF NOT EXISTS precio_original NUMERIC(12,2),
ADD COLUMN IF NOT EXISTS porcentaje_descuento NUMERIC(10,2) DEFAULT 0,
ADD COLUMN IF NOT EXISTS descuento_unitario NUMERIC(12,2) DEFAULT 0,
ADD COLUMN IF NOT EXISTS id_oferta INTEGER REFERENCES ofertas_categorias(id_oferta);
