ALTER TABLE sucursales
ADD COLUMN IF NOT EXISTS direccion TEXT;

ALTER TABLE sucursales
ADD COLUMN IF NOT EXISTS telefono VARCHAR(30);

ALTER TABLE sucursales
ADD COLUMN IF NOT EXISTS correo VARCHAR(150);

ALTER TABLE sucursales
ADD COLUMN IF NOT EXISTS responsable VARCHAR(150);

ALTER TABLE sucursales
ADD COLUMN IF NOT EXISTS activo BOOLEAN DEFAULT true;

ALTER TABLE sucursales
ADD COLUMN IF NOT EXISTS fecha_creacion TIMESTAMP DEFAULT CURRENT_TIMESTAMP;

ALTER TABLE sucursales
ADD COLUMN IF NOT EXISTS fecha_actualizacion TIMESTAMP DEFAULT CURRENT_TIMESTAMP;